### PR TITLE
implement some simple speedups

### LINKED ISSUE #5: fastqc-rs is much slower than Falco (a C++ version of fastqc)
Dear fastqc-rs team,

I ran a test using both falco and fastqc-rs but found fastqc-rs is much slower compare to falco (https://github.com/smithlabcode/falco): 40 million reads falco takes only 1.5 minutes while fastqc-rs takes 22 minutes. I think the needle tail library for reading fastq file is much faster than any other C/C++ library? Any idea to improve?

Many thanks,

Jianshu

### PR DESCRIPTION
**Pull request by nlhepler**
A few simple things:
- use a HashMap with a more performant hash function (this one is used by rustc, we don't need the cryptographic guarantees provided by the stdlib's HashMap. Do note it's the same underlying HashMap implementation [hashbrown] with a different hashing function swapped out)
- convert to vector histograms where possible (HashMaps are slow by comparison)
- avoid some obvious unnecessary allocations (allocations are slow, especially in inner loops)

This probably won't get us as fast as the C++ version (I am presuming that version is highly optimized _and_ I have not benchmarked it), but these changes do speed things up a fair amount.

Absolutely unscientifically benchmarked on a random 808MB FASTQ file we have lying around (output of `/usr/bin/time -v`):

Before:
```
        User time (seconds): 212.82
        System time (seconds): 2.17
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 3:35.80
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1357860
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 613038
        Voluntary context switches: 1965
        Involuntary context switches: 483
        Swaps: 0
        File system inputs: 20104
        File system outputs: 893376
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

After:
```
        User time (seconds): 104.35
        System time (seconds): 0.86
        Percent of CPU this job got: 98%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:46.31
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 240872
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 9630
        Voluntary context switches: 1526
        Involuntary context switches: 280
        Swaps: 0
        File system inputs: 61536
        File system outputs: 441008
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

PS: I did have to convert the base quality bits to a custom quartiles computation, which did have the advantage of allowing us to drop plotters (which brings in a huge number of complex dependencies).

### CODE REVIEW

**Comment by nlhepler** [comment]
Ahh, I was working from a previous version. Let me update to the latest main, rebenchmark, and rebase.

**Comment by nlhepler** [comment]
Okay, nothing major changes wrt findings.

**Comment by fxwiegand** [comment]
First of all thanks a lot for your efforts! I am very happy to have someone else contribute to this. 

> A few simple things:
> 
> * use a HashMap with a more performant hash function (this one is used by rustc, we don't need the cryptographic guarantees provided by the stdlib's HashMap. Do note it's the same underlying HashMap implementation [hashbrown] with a different hashing function swapped out)
> * convert to vector histograms where possible (HashMaps are slow by comparison)
> * avoid some obvious unnecessary allocations (allocations are slow, especially in inner loops)

Makes totally sense. Looks perfect! 

> PS: I did have to convert the base quality bits to a custom quartiles computation, which did have the advantage of allowing us to drop plotters (which brings in a huge number of complex dependencies).

Awesome! I was very unhappy to have the big plotters dependency but was a bit to lazy to compute the quartiles myself.


The overall test of the report is obviously failing since we changed the quartile calculation and some other stuff so we would need to update the expected files. If you don't want to update them i can simply merge this and update them on the main branch afterwards. Let me know and again thanks for your contribution!

Edit: I just realized i could just update the file in the PR myself 😅

**Review by fxwiegand — APPROVED** [review]

**Comment by jianshu93** [comment]
Hi All, any possibility to also make it parallel, like processing reads using multiple threads to be faster? I was under the impression that the algorithm is easily parallelized using rayon. 

Thanks,

Jianshu

**Pull request merged**
